app/urls.py
from django.urls import path
from app.views import *

app_name='style'

urlpatterns=[
    path('style/',style,name='style'),
    path('forgive/',forgive,name='forgive'),
]

app1/urls.py
from django.urls import path
from app1.views import *

app_name='kind'

urlpatterns=[
    path('kind/',kind,name='kind'),
    path('peace/',peace,name='peace')
]

surl_snav_ssf/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def style(request):
    return render(request,'style.html')
def forgive(request):
    return render(request,'forgive.html')

app1/views.py
from django.shortcuts import render

# Create your views here.


def kind(request):
    return render(request,'kind.html')
def peace(request):
    return render(request,'peace.html')

templates/forgive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>forgive every one then god will forgive you</h1>

    <a href="{% url 'style:style' %}">GO TO STYLE</a>
    <a href="{% url 'kind:kind' %}">kind</a>
    <a href="{% url 'kind:peace' %}">peace</a>
</body>
</html>

templates/kind.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>kind towards people</h1>
    </center>
    <a href="{% url 'style:style' %}">GO TO STYLE</a>
    <a href="{% url 'style:forgive' %}">kind</a>
    <a href="{% url 'kind:peace' %}">peace</a>
</body>
</html>

templates/peace.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>u will find peace in god presense</h1>

    <a href="{% url 'style:style' %}">GO TO STYLE</a>
    <a href="{% url 'kind:kind' %}">kind</a>
    <a href="{% url 'style:forgive' %}">peace</a>
</body>
</html>

templates/style.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <center>
        <h2>FOOTBALL</h2>
        <img src="{% static 'images/images.jpeg' %}" alt="">
    </center>
    <a href="{% url 'style:forgive' %}">GO TO STYLE</a>
    <a href="{% url 'kind:kind' %}">kind</a>
    <a href="{% url 'kind:peace' %}">peace</a>
</body>
</html>